# Generated by Django 4.2.7 on 2024-02-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsom_sga', '0002_userprofile_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dark_mode',
        ),
    ]
