# Generated by Django 4.2.7 on 2024-03-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsom_sga', '0003_remove_userprofile_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
