# Generated by Django 4.2.5 on 2023-11-06 02:29

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('contact', 'Category')
    Category.objects.get_or_create(name='Amigos')
    Category.objects.get_or_create(name='Família')
    Category.objects.get_or_create(name='Conhecido')

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contact_last_name_alter_contact_phone_and_more'),
    ]

    operations = [
    ]
