# Generated by Django 4.2.5 on 2023-12-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='idade',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
